[tasks.build]
command = "cargo"
args = ["build"]

[tasks.compile]
command = "cargo"
args = ["run"]

[tasks.assemble]
script = [
    "gcc -static a.s -o a.out",
]

[tasks.testml]
dependencies = [
    "run"
]
script = [
    "./target/debug/ruscaml ./tests/test.ml"
]

[tasks.unit_test]
dependencies = [
    "run"
]
script = [
    "./target/debug/ruscaml ./tests/onetest.ml"
]

[tasks.run]
dependencies = [
    "build",
    "assemble",
]