[tasks.build]
command = "cargo"
args = ["build"]

[tasks.compile]
command = "cargo"
args = ["run"]

[tasks.assemble]
script = [
    "gcc -static a.s -o a.out",
]

[tasks.testml]
dependencies = [
    "build"
]
script = [
    "./target/debug/ruscaml ./tests/one.ml"
]

[tasks.onetest]
dependencies = [
    "build"
]

script = [
    "aarch64-linux-gnu-gcc a.s -o a",
    "qemu-aarch64 -L /usr/aarch64-linux-gnu/ a",
]

[tasks.run]
dependencies = [
    "build",
    "assemble",
]